-- link 模型: EagleRcvr
-- 描述: project=eagle_rcvr
-- 源表(lim_raw): eagle_rcvr_raw
-- 目标表(lim_dwh): eagle_rcvr_dwd
-- 唯一键: FCoverSN
-- 执行: Worker 在 raw 跑本 SELECT（增量时按 ingested_at 过滤），再写入 dwh
--
SELECT
    NULLIF(BTRIM(("FCoverSN")::text), '') AS "FCoverSN",
    NULLIF(BTRIM(("ServerTime")::text), '')::timestamptz AS "ServerTime",
    NULLIF(BTRIM(("机台")::text), '') AS "机台",
    NULLIF(BTRIM(("模具模穴")::text), '') AS "模穴",
    NULLIF(BTRIM(("模仁")::text), '') AS "模仁",
    NULLIF(BTRIM(("线体")::text), '') AS "底涂线体",
    NULLIF(BTRIM(("线体1")::text), '') AS "自动外观线体",
    CASE WHEN lower(COALESCE(NULLIF(BTRIM(("B5合模线溢胶")::text), ''), '')) IN ('1','true','t','y','yes','ok','pass','合格','通过') THEN 1::smallint WHEN lower(COALESCE(NULLIF(BTRIM(("B5合模线溢胶")::text), ''), '')) IN ('0','false','f','n','no','ng','fail','不合格','失败') THEN 0::smallint ELSE NULL END AS "B5合模线溢胶",
    CASE WHEN lower(COALESCE(NULLIF(BTRIM(("B1缺胶气泡")::text), ''), '')) IN ('1','true','t','y','yes','ok','pass','合格','通过') THEN 1::smallint WHEN lower(COALESCE(NULLIF(BTRIM(("B1缺胶气泡")::text), ''), '')) IN ('0','false','f','n','no','ng','fail','不合格','失败') THEN 0::smallint ELSE NULL END AS "B1缺胶气泡",
    CASE WHEN lower(COALESCE(NULLIF(BTRIM(("结果_外长直边")::text), ''), '')) IN ('1','true','t','y','yes','ok','pass','合格','通过') THEN 1::smallint WHEN lower(COALESCE(NULLIF(BTRIM(("结果_外长直边")::text), ''), '')) IN ('0','false','f','n','no','ng','fail','不合格','失败') THEN 0::smallint ELSE NULL END AS "外长直边",
    CASE WHEN lower(COALESCE(NULLIF(BTRIM(("结果_正面硅胶")::text), ''), '')) IN ('1','true','t','y','yes','ok','pass','合格','通过') THEN 1::smallint WHEN lower(COALESCE(NULLIF(BTRIM(("结果_正面硅胶")::text), ''), '')) IN ('0','false','f','n','no','ng','fail','不合格','失败') THEN 0::smallint ELSE NULL END AS "正面硅胶",
    CASE WHEN lower(COALESCE(NULLIF(BTRIM(("结果_内长直边")::text), ''), '')) IN ('1','true','t','y','yes','ok','pass','合格','通过') THEN 1::smallint WHEN lower(COALESCE(NULLIF(BTRIM(("结果_内长直边")::text), ''), '')) IN ('0','false','f','n','no','ng','fail','不合格','失败') THEN 0::smallint ELSE NULL END AS "内长直边",
    CASE WHEN lower(COALESCE(NULLIF(BTRIM(("结果_反面烟囱")::text), ''), '')) IN ('1','true','t','y','yes','ok','pass','合格','通过') THEN 1::smallint WHEN lower(COALESCE(NULLIF(BTRIM(("结果_反面烟囱")::text), ''), '')) IN ('0','false','f','n','no','ng','fail','不合格','失败') THEN 0::smallint ELSE NULL END AS "反面烟囱",
    CASE WHEN lower(COALESCE(NULLIF(BTRIM(("结果_正面支架")::text), ''), '')) IN ('1','true','t','y','yes','ok','pass','合格','通过') THEN 1::smallint WHEN lower(COALESCE(NULLIF(BTRIM(("结果_正面支架")::text), ''), '')) IN ('0','false','f','n','no','ng','fail','不合格','失败') THEN 0::smallint ELSE NULL END AS "正面支架",
    CASE WHEN lower(COALESCE(NULLIF(BTRIM(("结果_反面边框")::text), ''), '')) IN ('1','true','t','y','yes','ok','pass','合格','通过') THEN 1::smallint WHEN lower(COALESCE(NULLIF(BTRIM(("结果_反面边框")::text), ''), '')) IN ('0','false','f','n','no','ng','fail','不合格','失败') THEN 0::smallint ELSE NULL END AS "反面边框",
    CASE WHEN lower(COALESCE(NULLIF(BTRIM(("结果_硅胶短边")::text), ''), '')) IN ('1','true','t','y','yes','ok','pass','合格','通过') THEN 1::smallint WHEN lower(COALESCE(NULLIF(BTRIM(("结果_硅胶短边")::text), ''), '')) IN ('0','false','f','n','no','ng','fail','不合格','失败') THEN 0::smallint ELSE NULL END AS "硅胶短边",
    CASE WHEN lower(COALESCE(NULLIF(BTRIM(("底涂")::text), ''), '')) IN ('1','true','t','y','yes','ok','pass','合格','通过') THEN 1::smallint WHEN lower(COALESCE(NULLIF(BTRIM(("底涂")::text), ''), '')) IN ('0','false','f','n','no','ng','fail','不合格','失败') THEN 0::smallint ELSE NULL END AS "底涂",
    CASE WHEN lower(COALESCE(NULLIF(BTRIM(("硅胶")::text), ''), '')) IN ('1','true','t','y','yes','ok','pass','合格','通过') THEN 1::smallint WHEN lower(COALESCE(NULLIF(BTRIM(("硅胶")::text), ''), '')) IN ('0','false','f','n','no','ng','fail','不合格','失败') THEN 0::smallint ELSE NULL END AS "硅胶",
    CASE WHEN lower(COALESCE(NULLIF(BTRIM(("定位")::text), ''), '')) IN ('1','true','t','y','yes','ok','pass','合格','通过') THEN 1::smallint WHEN lower(COALESCE(NULLIF(BTRIM(("定位")::text), ''), '')) IN ('0','false','f','n','no','ng','fail','不合格','失败') THEN 0::smallint ELSE NULL END AS "定位",
    CASE WHEN lower(COALESCE(NULLIF(BTRIM(("试模")::text), ''), '')) IN ('1','true','t','y','yes','ok','pass','合格','通过') THEN 1::smallint WHEN lower(COALESCE(NULLIF(BTRIM(("试模")::text), ''), '')) IN ('0','false','f','n','no','ng','fail','不合格','失败') THEN 0::smallint ELSE NULL END AS "试模",
    NULLIF(BTRIM((SUBSTRING(NULLIF(CASE WHEN lower(BTRIM("FCoverSN"::text)) IN ('nan','none','null','nat') THEN NULL ELSE BTRIM("FCoverSN"::text) END, '') FROM 13 FOR 2))::text), '') AS "本体",
    CASE WHEN lower(COALESCE(NULLIF(BTRIM((CASE WHEN NULLIF(TRIM("B2"::text), '') IS NULL AND NULLIF(TRIM("B2凹坑气泡1"::text), '') IS NULL AND NULLIF(TRIM("B2凹坑气泡"::text), '') IS NULL THEN NULL WHEN NULLIF(TRIM("B2"::text), '') = '1' OR NULLIF(TRIM("B2凹坑气泡1"::text), '') = '1' OR NULLIF(TRIM("B2凹坑气泡"::text), '') = '1' THEN '1' ELSE '0' END)::text), ''), '')) IN ('1','true','t','y','yes','ok','pass','合格','通过') THEN 1::smallint WHEN lower(COALESCE(NULLIF(BTRIM((CASE WHEN NULLIF(TRIM("B2"::text), '') IS NULL AND NULLIF(TRIM("B2凹坑气泡1"::text), '') IS NULL AND NULLIF(TRIM("B2凹坑气泡"::text), '') IS NULL THEN NULL WHEN NULLIF(TRIM("B2"::text), '') = '1' OR NULLIF(TRIM("B2凹坑气泡1"::text), '') = '1' OR NULLIF(TRIM("B2凹坑气泡"::text), '') = '1' THEN '1' ELSE '0' END)::text), ''), '')) IN ('0','false','f','n','no','ng','fail','不合格','失败') THEN 0::smallint ELSE NULL END AS "B2凹坑",
    CASE WHEN lower(COALESCE(NULLIF(BTRIM((CASE WHEN NULLIF(TRIM("结果_硅胶短边"::text),'') IS NULL AND NULLIF(TRIM("结果_反面边框"::text),'') IS NULL AND NULLIF(TRIM("结果_正面支架"::text),'') IS NULL AND NULLIF(TRIM("结果_反面烟囱"::text),'') IS NULL AND NULLIF(TRIM("结果_内长直边"::text),'') IS NULL AND NULLIF(TRIM("结果_正面硅胶"::text),'') IS NULL AND NULLIF(TRIM("结果_外长直边"::text),'') IS NULL THEN NULL WHEN NULLIF(TRIM("结果_硅胶短边"::text),'')='1' OR NULLIF(TRIM("结果_反面边框"::text),'')='1' OR NULLIF(TRIM("结果_正面支架"::text),'')='1' OR NULLIF(TRIM("结果_反面烟囱"::text),'')='1' OR NULLIF(TRIM("结果_内长直边"::text),'')='1' OR NULLIF(TRIM("结果_正面硅胶"::text),'')='1' OR NULLIF(TRIM("结果_外长直边"::text),'')='1' THEN '1' ELSE '0' END)::text), ''), '')) IN ('1','true','t','y','yes','ok','pass','合格','通过') THEN 1::smallint WHEN lower(COALESCE(NULLIF(BTRIM((CASE WHEN NULLIF(TRIM("结果_硅胶短边"::text),'') IS NULL AND NULLIF(TRIM("结果_反面边框"::text),'') IS NULL AND NULLIF(TRIM("结果_正面支架"::text),'') IS NULL AND NULLIF(TRIM("结果_反面烟囱"::text),'') IS NULL AND NULLIF(TRIM("结果_内长直边"::text),'') IS NULL AND NULLIF(TRIM("结果_正面硅胶"::text),'') IS NULL AND NULLIF(TRIM("结果_外长直边"::text),'') IS NULL THEN NULL WHEN NULLIF(TRIM("结果_硅胶短边"::text),'')='1' OR NULLIF(TRIM("结果_反面边框"::text),'')='1' OR NULLIF(TRIM("结果_正面支架"::text),'')='1' OR NULLIF(TRIM("结果_反面烟囱"::text),'')='1' OR NULLIF(TRIM("结果_内长直边"::text),'')='1' OR NULLIF(TRIM("结果_正面硅胶"::text),'')='1' OR NULLIF(TRIM("结果_外长直边"::text),'')='1' THEN '1' ELSE '0' END)::text), ''), '')) IN ('0','false','f','n','no','ng','fail','不合格','失败') THEN 0::smallint ELSE NULL END AS "外观总结果",
    CASE WHEN lower(COALESCE(NULLIF(BTRIM((CASE WHEN NULLIF(TRIM("定位"::text),'') IS NULL AND NULLIF(TRIM("试模"::text),'') IS NULL AND NULLIF(TRIM("硅胶"::text),'') IS NULL AND NULLIF(TRIM("底涂"::text),'') IS NULL THEN NULL WHEN NULLIF(TRIM("定位"::text),'')='1' OR NULLIF(TRIM("试模"::text),'')='1' OR NULLIF(TRIM("硅胶"::text),'')='1' OR NULLIF(TRIM("底涂"::text),'')='1' THEN '1' ELSE '0' END)::text), ''), '')) IN ('1','true','t','y','yes','ok','pass','合格','通过') THEN 1::smallint WHEN lower(COALESCE(NULLIF(BTRIM((CASE WHEN NULLIF(TRIM("定位"::text),'') IS NULL AND NULLIF(TRIM("试模"::text),'') IS NULL AND NULLIF(TRIM("硅胶"::text),'') IS NULL AND NULLIF(TRIM("底涂"::text),'') IS NULL THEN NULL WHEN NULLIF(TRIM("定位"::text),'')='1' OR NULLIF(TRIM("试模"::text),'')='1' OR NULLIF(TRIM("硅胶"::text),'')='1' OR NULLIF(TRIM("底涂"::text),'')='1' THEN '1' ELSE '0' END)::text), ''), '')) IN ('0','false','f','n','no','ng','fail','不合格','失败') THEN 0::smallint ELSE NULL END AS "排次总结果",
    NOW() AS etl_at
FROM "eagle_rcvr_raw"
